### PR TITLE
drop shadows removed from projects images

### PR DESCRIPTION
**Pull request by tanyapowell**
@EChesters @lili2311 
#### Changes
- Drop shadows removed from projects images
  image

### CODE REVIEW

**Comment by EChesters** [comment]
The grey border around the image needs to be removed as well.

**Comment by tanyapowell** [comment]
Page now looks like:
image

**Comment by lili2311** [comment]
The Findacure project now is blended into the page, this needs to have some sort of border.

**Comment by lili2311** [comment]
merge for now? we can fix IPPR project in a diff PR?

**Comment by tanyapowell** [comment]
:+1:

**Pull request merged**
