### PR TITLE
Copy tweaks: Update all references of non profits to "non-profits" for consistency.

### PR DESCRIPTION
**Pull request by krissy**
### Description

As agreed by web team/board, update all existing references to "non profits" or "nonprofits" to the correct term: i.e. **"non-profits"**.

**_Progress: 100%**_

---
### Tasks
- [x] Update all references of "non profit" / "nonprofit" / "non-profit" to ensure consistency.

### CODE REVIEW

**Comment by lili2311** [comment]
I think this might break [signup form](https://github.com/womenhackfornonprofits/whfnp/pull/5/files#diff-b5c729c3566238596aba77e08615e47dR88) but this is actually not in use yet. probably best to not change anything within that bit but change title and footer only.

Otherwise :+1:

**Comment by tanyapowell** [comment]
:shipit: :+1:

**Comment by krissy** [comment]
Feedback addressed. Since it's quite a massive diff will see if everyone gives the ok on slack before merging.

**Comment by khandelwalrinki** [comment]
Looks good to me.

**Pull request merged**
