### PR TITLE
Bootstrap path

### PR DESCRIPTION
**Pull request by EChesters**
Changes include adding to the bootstrap paths as discussed earlier. 

_Tested locally_

### CODE REVIEW

**Comment by tanyapowell** [comment]
This seems to also include all the changes you made in #65. Could you take a look?

**Comment by EChesters** [comment]
The Issue 57 stuff has now been merged, not sure why it's in here as well. I think I did an emergency branch off the wrong one.

**Comment by tanyapowell** [comment]
Fair enough. I'll leave @lili2311 to take a look at this though, because I can't deploy to dev and also unsure about the bootstrap paths myself

**Comment by lili2311** [comment]
@EChesters i am hesitant to merge this as I am not sure if this will override the changes made in the other PR that was already merged, could you please raise a PR with just the path change so that we are sure what will be applied when we merge? I am afraid I don't know how git will handle this.

**Pull request closed without merging**
