### PR TITLE
Updated README

### PR DESCRIPTION
**Pull request by lili2311**
@womenhackfornonprofits/whfnp
## What are the changes included in this PR?

Updated README with the new instructions to watch for fron tend changes

### CODE REVIEW

**Comment by EChesters** [comment]
The above line where you;ve changed needs to be updated as well: 
`In order for Jekyll to watch and compile all the changes to html run jekyll serve in the src directory`

This is where I hit the issue.

**Comment by lili2311** [comment]
@EChesters the command does both jekyll serve and sass watch for you, please see here: https://github.com/womenhackfornonprofits/whfnp/blob/dev/Gruntfile.js#L203
and the concurrent serve command: https://github.com/womenhackfornonprofits/whfnp/blob/dev/Gruntfile.js#L184 compiles both Jekyll templates and sass.

So running `grunt` or `grunt default` is all you need (both do the same thing)

**Comment by EChesters** [comment]
I understand it does both, but the line I highlighted does not work. It's now redundant and needs to be removed. 

To run, we should not use `jekyll serve` like the README file still states after your change.

**Comment by lili2311** [comment]
😫  i see it now, thanks! pushing update

**Comment by lili2311** [comment]
Updated

**Comment by EChesters** [comment]
Approved 👍

**Pull request merged**
